source 'https://rubygems.org'

gem 'reel', github: 'celluloid/reel', branch: '0.6.0-milestone'
gem 'angelo', github: 'kenichi/angelo', branch: 'reel_0.6'
gem 'awesome_print'
gem 'cinch'
gem 'connection_pool'
gem 'daemons'
gem 'http'
gem 'redis'
gem 'redis-namespace', require: 'redis/namespace'
gem 'celluloid-redis'
gem 'pry'
